### ISSUE TITLE
Mpd doesn’t always start when mopidy is run as daemon

### ISSUE THREAD

**Issue by mgrouch** [mopidy/mopidy-mpd#26]
I can’t quite figure out the pattern. 
I use raspbian buster,
There is Spotify plugin. 
no errors in the log. 

Thanks,
—MG

**Comment by kingosticks** [comment]
Can you provide a more information, there's far too little detail here to help. Please read through https://docs.mopidy.com/en/latest/troubleshooting/

**Comment by mgrouch** [comment]
I think I've found conditions when it happens. If at start up it can't connect to spotify 
it fails to initialize MPD. The server comes up but never recovers even after spotify becomes
available. It seems some re-try logic is missing in the code.

Is easy to reproduce on my raspberry pi. If I shut it down, power off, then power on
when I get to play anything it can't connect to MPD.

If I reboot without powering off then it comes up fine (I guess network comes up faster
in that case)

I've put an ugly workaround into 

/usr/lib/systemd/system/mopidy.service

with 'while loop'

ExecStart=sh -c 'while ! ping -c 1 -n -w 1 spotify.com; do sleep 5; done;/usr/bin/mopidy --option mpd/enabled=true --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf'

See more details here:

https://bareboat-necessities.github.io/my-bareboat/#_music_player

Thanks,
--MG

**Comment by kingosticks** [comment]
With raspbian you should be setting the "Wait for network" option in raspi-config. With that, this workaround should not be necessary.

If you want to investigate the real issue that the MPD frontend somehow requires The Spotify backend to start correctly then please reopen and provide all the requested info as per the troubleshooting page, including a debug log file that shows the issue occurring. Thanks

**Comment by kingosticks** [comment]
For what it's worth, I cannot reproduce this. Starting Mopidy without network access does naturally mean Spotify fails to login, but otherwise Mpoidy is usable. 

```
MainThread INFO     2020-04-01 15:58:58,620 Starting Mopidy 3.0.1-24-gdc97f52f
MainThread INFO     2020-04-01 15:58:59,331 Loading config from builtin defaults
MainThread INFO     2020-04-01 15:58:59,335 Loading config from file:///home/nick/.config/mopidy/mopidy.conf
MainThread INFO     2020-04-01 15:58:59,335 Loading config from command line options
MainThread INFO     2020-04-01 15:58:59,539 Enabled extensions: mpd, musicbox_webclient, stream, local, spotify, file, m3u, iris, http, tunein, softwaremixer
MainThread INFO     2020-04-01 15:58:59,540 Disabled extensions: gmusic, mpris
MainThread INFO     2020-04-01 15:58:59,613 Starting Mopidy audio
MainThread INFO     2020-04-01 15:58:59,614 Starting Mopidy backends: SpotifyBackend, TuneInBackend, LocalBackend, FileBackend, M3UBackend, StreamBackend
Audio-1 INFO     2020-04-01 15:58:59,633 Audio output set to "autoaudiosink"
SpotifyEventLoop ERROR    2020-04-01 15:58:59,696 Spotify login error: <ErrorType.OTHER_PERMANENT: 10>
SpotifyBackend-2 ERROR    2020-04-01 15:59:01,199 OAuth token refresh failed: Unknown error.
SpotifyBackend-2 ERROR    2020-04-01 15:59:01,200 Failed to load Spotify user profile
MainThread INFO     2020-04-01 15:59:01,203 Starting Mopidy core
MainThread INFO     2020-04-01 15:59:01,225 Starting Mopidy frontends: MpdFrontend, IrisFrontend, HttpFrontend
MainThread INFO     2020-04-01 15:59:01,229 MPD server running at [::]:6601
HttpFrontend-14 INFO     2020-04-01 15:59:01,234 HTTP server running at [::]:6681
MainThread INFO     2020-04-01 15:59:01,235 Starting GLib mainloop
IrisFrontend-12 INFO     2020-04-01 15:59:01,235 Starting Iris 3.44.0
MpdSession-16 INFO     2020-04-01 16:00:18,323 New MPD connection from [::ffff:127.0.0.1]:58102
```

**Comment by mgrouch** [comment]
Does it re-login when network comes up? Or you have to restart it? 

Let’s say it comes up with Spotify failed to login and after that network is up. Can you see your Spotify lists and play them or you need restart?

Thanks

**Comment by kingosticks** [comment]
The Spotify backend does not try to login again once the initial login failed. You should start Mopidy once your network is working.

**Comment by mgrouch** [comment]
It should recover without restart when it can reach Spotify if a user tries to play something on Spotify. 
Network can go up and down. When it’s up Spotify should work. When network is down Spotify can’t play. 
But the server should be started only once at boot time. Users should not be expected to bounce it. 

Thanks,
—MG

**Comment by kingosticks** [comment]
Assuming network was up when Mopidy started, the network later going down and back up again is a reasonable use case and already fully supported. 

I do not think that attempting to start a service that requires the network when your network is not yet available is a valid use case.

**Comment by mgrouch** [comment]
Lets say I’m the user. I’m not admin. Admin turned on pi and everything started. Network at start time wasn’t avail. could be we were out of cell reception zone or whatever. Now it’s available and I as a user trying to play a song. Spotify is available but I can’t play it on mopidy. And as a user I do not have permission to restart it. 
 
Thanks,
—MG
