### ISSUE TITLE
Unable to list by various valid tags

### ISSUE THREAD

**Issue by kingosticks** [mopidy/mopidy-mpd#29]
Running the command:

> list title

should list all track names but it errors with:

> LocalBackend-3 ERROR    2020-04-17 23:06:06,116 Error getting distinct track: Invalid search field: track

And that's because we are incorrectly mapping MPD's 'title' tag to 'track' instead of 'track_name' but Mopidy-Local is rightly expecting 'track_name'. 

Also the tags 'track' and 'file' (and 'filename') are not supported. For example, running the command:

> list track

should list all the track numbers but it errors with:

> ACK [2@0] {list} Unknown tag type: track

Those are just missing from the mapping structure.

**Comment by LevitatingBusinessMan** [comment]
Seems like you had already fixed the `title` tag?

I think for `file` and `track` (regarding the track number) we need changes in `mopidy` as well? Regarding this dictionary: https://github.com/mopidy/mopidy/blob/develop/mopidy/internal/validation.py#L34-L43.

**Comment by kingosticks** [comment]
One of those tagged issues is about the Mopidy changes. It's currently on blocked on something I stated and didn't finish. I'll try and take a look later.
