### ISSUE TITLE
Can't Get Visualizations To Work

### ISSUE THREAD

**Issue by grravity** [mopidy/mopidy-mpd#34]
I currently have Mopidy-MPD and NCMPCPP. If I run mpd + ncmcpp, visualizations work. If I run mopidy (+mopidy-mpd) + ncmpcpp instead, visualizations don't work. I assume this is because Mopidy-MPD is completely separate from mpd as stated, so the mpd.conf isn't being read.

This leaves me with two questions. Can I link my mpd.conf to mopidy-mpd, I assume if I could have mopidy-mpd push the lines for fifo it would work, but I can't because idk where to put these lines seeing it's not using the mpd.conf.

Secondly, is it possible to just use regular mpd alongside mopidy? I assume this would allow more features, but I assume it's not possible and thats why this plugin was made? I need mopidy to do streaming over jellyfin/airsonic. I'm still a bit new to MPD, Mopidy and NCMPCPP so these could be something basic, or there could be a better way to do this. Would appreciate it.

**Comment by adamcik** [comment]
This feature is not supported. https://github.com/mopidy/mopidy/issues/775 is in theory what someone would need to fix to add support, but nobody is working on it, and most people on the bug have just focused on workarounds, not fixes.

You could run mopidy and mpd at the same time with different ports, but they would not work together in any way. Mopidy has nothing to do with MPD other than supporting a subset of the MPD protocol.

**Comment by arybczak** [comment]
It's fixed in ncmpcpp, see https://github.com/mopidy/mopidy/issues/775#issuecomment-747725806.
