### ISSUE TITLE
error adding stream

### ISSUE THREAD

**Issue by kindlydodo** [mopidy/mopidy-mpd#65]
I use mpdroid. I want to add a youtube stream, like this :

    yt:https://www.youtube.com/watch?v=tSv04ylc6To

this don't work. 
Logs:
`
Mar 16 11:08:42 raspberrypi mopidy[19844]: INFO     [MpdSession-74 (_actor_loop)] mopidy_mpd.session New MPD connection from [::ffff:192.168.1.100]:47752
Mar 16 11:08:42 raspberrypi mopidy[19844]: ERROR    [YouTubeBackend-5 (_actor_loop)] mopidy_youtube Cannot load youtube:video:tSv04ylc6To/
Mar 16 11:08:42 raspberrypi mopidy[19844]: ERROR    [YouTubeBackend-5 (_actor_loop)] mopidy_youtube Cannot load youtube:video:tSv04ylc6To/
`

**Comment by kingosticks** [comment]
Please open this issue at the mopidy-youtube project rather than there.

**Comment by kindlydodo** [comment]
Does mopidy-mpd choose mopidy-youtube as the backend in case of a youtube url? Im not sure if this is the case, because of the logs.

In my other mdp frontends (musicbox) adding streams like this works well, also, the logs are diffrent: mopidy-youtube outputs logs itself...when using mpdroid, mopidy-youtube does not log, so its not used? I guess mopidy-mpd has its own implementation?

How could i set which backen to chose per stream in mopidy-mpd?

**Comment by kingosticks** [comment]
Not quite. The frontend (http or mpd or whatever) tells Mopidy Core to add the stream and Mopidy Core selects the appropriate backend. The fronted (e.g. Mopidy-mpd) has no direct part in selecting the backend. Your log shows messages from YouTube so Core has done the right thing, in that respect.

However, the Core API that Mopidy-mpd uses might be slightly different to the web client, so it's possible there is an issue there.

If you can please provide more information:  your versions, *debug* log, and any other useful context, then we can reopen and look at this ( https://docs.mopidy.com/stable/troubleshooting/). The fact that the same thing works in another client is important context. If you can't provide a debug log then you need to provide the EXACT steps to reproduce the problem.
