### ISSUE TITLE
Can't use mopidy-mpd with Cantata

### ISSUE THREAD

**Issue by Hate9** [mopidy/mopidy-mpd#67]
Ok so I'm trying to do this with mopidy-jellyfin, so it's *possible* that this is an issue with *that*, but I'm not sure.

When Cantata tries to list my music from mopidy, it appears to run the command `lsinfo "Local media"`.
```
DEBUG    2024-04-30 19:52:12,642 [15766:MpdSession-15 (_actor_loop)] mopidy_mpd.session
  Request from [::ffff:127.0.0.1]:45106: lsinfo "Local media"
DEBUG    2024-04-30 19:52:12,643 [15766:MpdSession-15 (_actor_loop)] mopidy_mpd.session
  Response to [::ffff:127.0.0.1]:45106: ACK [50@0] {lsinfo} Not found
```
However, that returns `Not Found`.
I can see the folders in Cantata's "Server Folders" viewer, and mopidy-mpd appears to be serving my music under `Jellyfin/Music`. 
![image](https://github.com/mopidy/mopidy-mpd/assets/4684153/ebd631db-2cd0-4217-be81-03565c5d3581)
I can even play these files from here, but they still aren't showing in my library, and if I click "refresh database" in Cantata it throws the "Not found" error.

Is there some way of working around this? Is there a setting I need to change in Cantata? Or in mopidy-mpd, or possibly in mopidy-jellyfin?

**Comment by kingosticks** [comment]
It's a broken "feature" of Canata. See https://github.com/CDrummond/cantata/blob/af04723c0ca7854df53562ed8226fd324d6a23cd/mpd-interface/mpdconnection.cpp#L2797

**Comment by kingosticks** [comment]
I really have no idea why it works this way with hard-coded directory names, the MPD protocol shouldn't require this. Sadly it's not longer maintained so it won't be fixed.

**Comment by Hate9** [comment]
eh, well, I already use a fork, so I'll just pr a fix in that. thanks!
