### ISSUE TITLE
Newline-Characters in ID3-Tag-Fields are not escaped

### ISSUE THREAD

**Issue by lukasvogel** [mopidy/mopidy-mpd#7]
When playing a song which has a ID3-Tag-Field with multiple files (i.E. the one that produced this log: http://pastebin.com/CZ8UF6Z6), the newlines won't get escaped. This results in clients not accepting the sent message is it is not conforming with the protocol.

**Comment by jodal** [comment]
The merged PR #54 removes all ASCII control characters from MPD responses.
